In [38]:
import numpy as np
import pandas as pd
cashflows  = np.matrix("75 85 48 66 110; 374 562 400 492 532;37 111 104 114 46;74 222 208 228 92;56 98 76 90 78")
prices =  np.matrix("309 1918 341 682 325")

In [39]:
for row in matrix:
    print(row)
    print(row/matrix[0])
    print(row/matrix[1])
    print(row/matrix[2])
    print(row/matrix[3])
    print(row/matrix[4])


[[ 75  85  48  66 110]]
[[1. 1. 1. 1. 1.]]
[[0.20053476 0.15124555 0.12       0.13414634 0.20676692]]
[[2.02702703 0.76576577 0.46153846 0.57894737 2.39130435]]
[[1.01351351 0.38288288 0.23076923 0.28947368 1.19565217]]
[[1.33928571 0.86734694 0.63157895 0.73333333 1.41025641]]
[[374 562 400 492 532]]
[[4.98666667 6.61176471 8.33333333 7.45454545 4.83636364]]
[[1. 1. 1. 1. 1.]]
[[10.10810811  5.06306306  3.84615385  4.31578947 11.56521739]]
[[5.05405405 2.53153153 1.92307692 2.15789474 5.7826087 ]]
[[6.67857143 5.73469388 5.26315789 5.46666667 6.82051282]]
[[ 37 111 104 114  46]]
[[0.49333333 1.30588235 2.16666667 1.72727273 0.41818182]]
[[0.09893048 0.1975089  0.26       0.23170732 0.08646617]]
[[1. 1. 1. 1. 1.]]
[[0.5 0.5 0.5 0.5 0.5]]
[[0.66071429 1.13265306 1.36842105 1.26666667 0.58974359]]
[[ 74 222 208 228  92]]
[[0.98666667 2.61176471 4.33333333 3.45454545 0.83636364]]
[[0.19786096 0.39501779 0.52       0.46341463 0.17293233]]
[[2. 2. 2. 2. 2.]]
[[1. 1. 1. 1. 1.]]
[[1.32142857 